[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
renderXml = true
index = win_logs

[WinEventLog://Security]
disabled = 0
index = win_logs

[WinEventLog://System]
disabled = 0
index = win_logs